---
title: "Plottings outputs of the cellrank analysis"
author: Nick Negretti
date: 12/07/20
output:
  html_document:
    df_print: paged
    toc: true
    toc_float:
      toc_collapsed: false
    toc_depth: 3
    number_sections: false
    theme: lumen
---

```{css toc-content, echo = FALSE}

.main-container {
    margin-left: 20px;
}
.tocify-extend-page {
  height: 0 !important;
}
```
# Plot cellrank outputs of the lung endothelium

## Load libraries and helper functions
```{r, results="hide", message = FALSE}
setwd("~/postdoc/code/devo_scseq")

source("./helper_functions/libraries.R")

opts_knit$set(root.dir = getwd())

source("./helper_functions/trajectory.R")
source("./helper_functions/cluster.R")
source("./helper_functions/colors.R")

source("./helper_functions/brackets.R")
source("./helper_functions/heatmaps.R")
set.seed(42) # For reproducability

N_WORKERS <- 3
options(future.globals.maxSize=2048*1024^2)
plan("multiprocess", workers = N_WORKERS)
```
## Load data from merge and clean pipeline
```{r}
cellrank_out <- anndata::read_h5ad("./velocity/epi/only_metadata.h5ad")
ggdata_epi <- data.frame(x = cellrank_out$obsm$X_umap[,1],
                          y = cellrank_out$obsm$X_umap[,2],
                          velocity_length = cellrank_out$obs$velocity_length,
                          group = as.character(cellrank_out$obs$cell_subtype),
                          timepoint = as.character(cellrank_out$obs$timepoint))

cellrank_out <- anndata::read_h5ad("./velocity/endo/only_metadata.h5ad")
ggdata_endo <- data.frame(x = cellrank_out$obsm$X_umap[,1],
                          y = cellrank_out$obsm$X_umap[,2],
                          velocity_length = cellrank_out$obs$velocity_length,
                          group = as.character(cellrank_out$obs$cell_subtype),
                          timepoint = as.character(cellrank_out$obs$timepoint))


cellrank_out <- anndata::read_h5ad("./velocity/meso/with_latent_time.h5ad")
ggdata_meso <- data.frame(x = cellrank_out$obsm$X_umap[,1],
                          y = cellrank_out$obsm$X_umap[,2],
                          velocity_length = cellrank_out$obs$velocity_length,
                          group = as.character(cellrank_out$obs$cell_subtype),
                          timepoint = as.character(cellrank_out$obs$timepoint))


```

```{r}
cellrank_out
```

```{r}
meso_ms <- Matrix::readMM("./velocity/meso/meso_expression_Ms.mtx.gz")
```


```{r}
gene <- "Plin2"
include_celltypes <- c("Proliferating *Wnt2*+ FB", "*Wnt2*+ FB", "Proliferating myofibroblast", "Myofibroblast")
exp_over_time <- data.frame(expression = meso_ms[,colnames(cellrank_out) == gene],
                            Cluster = cellrank_out$obs$cell_subtype,
                            latent_time = cellrank_out$obs$latent_time
)

unique(exp_over_time$Cluster)

levels(exp_over_time$Cluster)[levels(exp_over_time$Cluster) == "Prenatal Wnt2+"] <- "Proliferating *Wnt2*+ FB"
levels(exp_over_time$Cluster)[levels(exp_over_time$Cluster) == "Wnt2+"] <- "*Wnt2*+ FB"
levels(exp_over_time$Cluster)[levels(exp_over_time$Cluster) == "Prenatal Myofibroblast"] <- "Proliferating myofibroblast"

exp_over_time$Cluster <- ordered(as.factor(exp_over_time$Cluster), c("Proliferating *Wnt2*+ FB", "*Wnt2*+ FB", "Proliferating myofibroblast", "Myofibroblast", "Adventitial fibroblast", "Pericyte", "Mesothelium", "Smooth muscle", "Neuron"))

exp_over_time <- exp_over_time[exp_over_time$Cluster %in% include_celltypes,]

plin2_exp <- ggplot(exp_over_time, aes(y = expression, x = latent_time, color = Cluster)) +
  geom_point(alpha = 0.5) +
  scale_color_manual(aesthetics = c("color", "fill"), values= color_category_20[1:4], guide = guide_legend(override.aes = list(size=3), order = 1)) +
  theme(legend.key = element_blank(),
        legend.text = element_markdown(size=14),
        legend.title = element_markdown(size=16),
        #axis.text.x  = element_text(size=14),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        axis.text.y = element_text(size=14),
        axis.title.x = element_text(size=14, vjust = -1),
        axis.title.y = element_text(size=14),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.background = element_rect(fill = "white", color = "black"),
        aspect.ratio = 0.8,
        plot.title = element_markdown(size = 16)
  ) +
  scale_x_continuous(breaks = c(0,1)) +
  ylab("Expression") +
  xlab("Latent time") +
  ggtitle(paste0("*", gene, "*"))

plin2_exp

```


```{r}
gene <- "Tgfbi"
include_celltypes <- c("Proliferating *Wnt2*+ FB", "*Wnt2*+ FB", "Proliferating myofibroblast", "Myofibroblast")
exp_over_time <- data.frame(expression = meso_ms[,colnames(cellrank_out) == gene],
                            Cluster = cellrank_out$obs$cell_subtype,
                            latent_time = cellrank_out$obs$latent_time
)

unique(exp_over_time$Cluster)

levels(exp_over_time$Cluster)[levels(exp_over_time$Cluster) == "Prenatal Wnt2+"] <- "Proliferating *Wnt2*+ FB"
levels(exp_over_time$Cluster)[levels(exp_over_time$Cluster) == "Wnt2+"] <- "*Wnt2*+ FB"
levels(exp_over_time$Cluster)[levels(exp_over_time$Cluster) == "Prenatal Myofibroblast"] <- "Proliferating myofibroblast"

exp_over_time$Cluster <- ordered(as.factor(exp_over_time$Cluster), c("Proliferating *Wnt2*+ FB", "*Wnt2*+ FB", "Proliferating myofibroblast", "Myofibroblast", "Adventitial fibroblast", "Pericyte", "Mesothelium", "Smooth muscle", "Neuron"))

exp_over_time <- exp_over_time[exp_over_time$Cluster %in% include_celltypes,]

tgfbi_exp <- ggplot(exp_over_time, aes(y = expression, x = latent_time, color = Cluster)) +
  geom_point(alpha = 0.5) +
  scale_color_manual(aesthetics = c("color", "fill"), values= color_category_20[1:4], guide = guide_legend(override.aes = list(size=3), order = 1)) +
  theme(legend.key = element_blank(),
        legend.text = element_markdown(size=14),
        legend.title = element_markdown(size=16),
        #axis.text.x  = element_text(size=14),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        axis.text.y = element_text(size=14),
        axis.title.x = element_text(size=14, vjust = -1),
        axis.title.y = element_text(size=14),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.background = element_rect(fill = "white", color = "black"),
        aspect.ratio = 0.8,
        plot.title = element_markdown(size = 16)
  ) +
  scale_x_continuous(breaks = c(0,1)) +
  ylab("Expression") +
  xlab("Latent time") +
  ggtitle(paste0("*", gene, "*"))

tgfbi_exp

```



```{r}
tiff("./figures/meso/plin2_tgfbi.tiff", width = 15, height = 4, units = "in", res = 600, compression = "lzw", bg = "transparent")
plin2_exp + tgfbi_exp + plot_layout(ncol = 2, nrow = 1, guides = "collect")
dev.off()

```

```{r}
ggdata_meso <- data.frame(x = cellrank_out$obsm$X_umap[,1],
                     y = cellrank_out$obsm$X_umap[,2],
                     velocity_length = cellrank_out$obs$velocity_length,
                     group = as.character(cellrank_out$obs$cell_subtype),
                     timepoint = as.character(cellrank_out$obs$timepoint))
head(ggdata_meso)
colnames(ggdata_meso) <- c("x", "y", "velocity_length", "group", "timepoint")
mean(ggdata_meso$velocity_length)
mean(ggdata_meso$velocity_length[cellrank_out$obs$cell_subtype == "Prenatal Wnt2+"])

ggplot(ggdata_meso %>% arrange(velocity_length), aes(x = x, y = y, color = velocity_length)) + geom_point() + umap_theme() + theme(aspect.ratio = 1) + scale_color_viridis()

```

```{r}
ggdata_meso$macro_celltype <- "Mesenchyme"
ggdata_endo$macro_celltype <- "Endothelium"
ggdata_epi$macro_celltype <- "Epithelium"

ggdata_all <- rbind(ggdata_meso, ggdata_endo, ggdata_epi)
head(ggdata_all)

dropLessThan10 <- function(x, pct_cutoff = 0.1){
  keep_ids <- c()
  tot_len <- nrow(x)

  for (g in unique(x$group)){
    for (t in unique(x$timepoint)){
      ids <- which(x$group == g & x$timepoint == t)
      if ((length(ids) / tot_len) * 100 > pct_cutoff){
        keep_ids <- c(keep_ids, ids)
      }
    }
  }
  return(x[keep_ids,])
}



```

```{r}
ggdata_alveolar_epi <- ggdata_all[ggdata_all$group %in% c("Primordial",
                                                          "Transitional",
                                                          "Type II",
                                                          "Type I"),]

ggdata_alveolar_epi[ggdata_alveolar_epi$group == "Type II",'group'] <- "AT2"
ggdata_alveolar_epi[ggdata_alveolar_epi$group == "Type I",'group'] <- "AT1"

ggdata_alveolar_epi <- ggdata_alveolar_epi[!(ggdata_alveolar_epi$group == "Primordial" & ggdata_alveolar_epi$timepoint %in% c("P3", "P5", "P7", "P14")),]
#ggdata_alveolar <- dropLessThan10(ggdata_alveolar, 0)
ggdata_alveolar_epi$group <- ordered(as.factor(ggdata_alveolar_epi$group), c("Primordial", "Transitional", "AT1", "AT2"))

alveolar_velocity_summary_epi <- ggdata_alveolar_epi %>% group_by(group,timepoint,macro_celltype) %>% summarise(mean_velocity=mean(velocity_length),
                                                                                    median_velocity=median(velocity_length))
alveolar_velocity_summary_epi$timepoint <- ordered(as.factor(alveolar_velocity_summary_epi$timepoint), c("E12", "E15", "E18", "P0", "P3", "P5", "P7", "P14"))


rna_total_velocity <- ggplot(ggdata_alveolar_epi, aes(x = timepoint, y = velocity_length, fill = group)) +
        geom_line(data = alveolar_velocity_summary_epi,
                  aes(x = timepoint, y = median_velocity, group = group, color = group),
                  position = position_dodge(width = 0.5)) +
        geom_boxplot(width = 0.8, position = position_dodge2(preserve = "single", padding = 0.1), outlier.size = 0.2) +
        prism_theme() +
        theme(aspect.ratio = 0.8,
              panel.grid.minor.y = element_blank(),
              panel.grid.major.y = element_blank(),
              panel.grid.minor.x = element_blank(),
              panel.grid.major.x = element_blank(),
              legend.text = element_text(size = 12),
              legend.title = element_text(size = 12)
        ) +
        ylab("RNA velocity length") +
        labs(fill = "Cell type") +
        scale_color_manual(guide = "none",
                           values = c("#1f77b4", # Dark blue
                                      "#aec7e8", # Light blue
                                      "#2ca02c", # Dark green
                                      "#98df8a" # Light green
                           )) +
        scale_fill_manual(values = c("#1f77b4", # Dark blue
                                     "#aec7e8", # Light blue
                                     "#2ca02c", # Dark green
                                     "#98df8a" # Light green
        )) +
        ylim(5,25)
rna_total_velocity

pdf("./figures/epi/epi_velocity_summary.pdf", width = 6, height = 4)
rna_total_velocity
dev.off()

```


```{r}

ggdata_alveolar_endo <- ggdata_all[ggdata_all$group %in% c("Car4+",
                                                           "miEC"),]
ggdata_alveolar_endo[ggdata_alveolar_endo$group == "Car4+",'group'] <- "*Car4*+"
#ggdata_alveolar <- dropLessThan10(ggdata_alveolar, 0.1)

alveolar_velocity_summary_endo <- ggdata_alveolar_endo %>% group_by(group,timepoint,macro_celltype) %>% summarise(mean_velocity=mean(velocity_length),
                                                                                         median_velocity=median(velocity_length))
alveolar_velocity_summary_endo$timepoint <- ordered(as.factor(alveolar_velocity_summary_endo$timepoint), c("E12", "E15", "E18", "P0", "P3", "P5", "P7", "P14"))


rna_total_velocity <- ggplot(ggdata_alveolar_endo, aes(x = timepoint, y = velocity_length, fill = group)) +
        geom_line(data = alveolar_velocity_summary_endo,
                  aes(x = timepoint, y = median_velocity, group = group, color = group),
                  position = position_dodge(width = 0.5)) +
        geom_boxplot(width = 0.5, position = position_dodge2(preserve = "single", padding = 0.1), outlier.size = 0.2) +
        prism_theme() +
        theme(aspect.ratio = 0.8,
              panel.grid.minor.y = element_blank(),
              panel.grid.major.y = element_blank(),
              panel.grid.minor.x = element_blank(),
              panel.grid.major.x = element_blank(),
              legend.text = element_markdown(size = 12),
              legend.title = element_text(size = 12)
        ) +
        ylab("RNA velocity length") +
        labs(fill = "Cell type") +
        scale_color_manual(guide = "none",
                     values = c("#ff7f0e", # Light orange
                                "#ffbb78" # Dark orange
                     )) +
        scale_fill_manual(values = c("#ff7f0e", # Light orange
                                     "#ffbb78" # Dark orange
        )) +
        ylim(5,25)
rna_total_velocity

pdf("./figures/endo/endo_velocity_summary.pdf", width = 6, height = 4)
rna_total_velocity
dev.off()

```


```{r}
ggdata_all[ggdata_all$group == "Prenatal Myofibroblast",'group'] <- "Myofibroblast"
ggdata_all[ggdata_all$group == "Prenatal Wnt2+",'group'] <- "*Wnt2*+ FB"

ggdata_alveolar_meso <- ggdata_all[ggdata_all$group %in% c("Myofibroblast",
                                                      "*Wnt2*+ FB"),]

#ggdata_alveolar <- dropLessThan10(ggdata_alveolar, 0.1)

alveolar_velocity_summary_meso <- ggdata_alveolar_meso %>% group_by(group,timepoint,macro_celltype) %>% summarise(mean_velocity=mean(velocity_length),
                                                                                         median_velocity=median(velocity_length))
alveolar_velocity_summary_meso$timepoint <- ordered(as.factor(alveolar_velocity_summary_meso$timepoint), c("E12", "E15", "E18", "P0", "P3", "P5", "P7", "P14"))


rna_total_velocity <- ggplot(ggdata_alveolar_meso, aes(x = timepoint, y = velocity_length, fill = group)) +
        geom_line(data = alveolar_velocity_summary_meso,
                  aes(x = timepoint, y = median_velocity, group = group, color = group),
                  position = position_dodge(width = 0.5)) +
        geom_boxplot(width = 0.5, position = position_dodge2(preserve = "single", padding = 0.1), outlier.size = 0.2) +
        prism_theme() +
        theme(aspect.ratio = 0.8,
              panel.grid.minor.y = element_blank(),
              panel.grid.major.y = element_blank(),
              panel.grid.minor.x = element_blank(),
              panel.grid.major.x = element_blank(),
              legend.text = element_markdown(size = 12),
              legend.title = element_text(size = 12)
        ) +
        ylab("RNA velocity length") +
        labs(fill = "Cell type") +
        scale_color_manual(guide = "none",
                     values = c("#d62728", # Dark red
                                "#ff9896" # Light red
                     )) +
        scale_fill_manual(values = c("#d62728", # Light orange
                                     "#ff9896" # Dark orange
        )) +
        ylim(5,25)
rna_total_velocity

pdf("./figures/meso/meso_velocity_summary.pdf", width = 6, height = 4)
rna_total_velocity
dev.off()

```


```{r}



rna_total_velocity <- ggplot() +
        geom_line(data = alveolar_velocity_summary_epi,
                  aes(x = timepoint, y = median_velocity, group = group, color = group),
                  position = position_dodge(width = 0.5)) +
        geom_boxplot(data = ggdata_alveolar_epi, aes(x = timepoint, y = velocity_length, color = group),
                     width = 0.5, position = position_dodge2(preserve = "single", padding = 0.1)) +
        scale_color_manual(guide = guide_legend(reverse = FALSE),
                           values = c("#1f77b4", # Dark blue
                                      "#aec7e8", # Light blue
                                      "#2ca02c", # Dark green
                                      "#98df8a" # Light green
                           )) +
        new_scale_color() +
        geom_line(data = alveolar_velocity_summary_endo,
                  aes(x = timepoint, y = median_velocity, group = group, color = group),
                  position = position_dodge(width = 0.5)) +
        geom_boxplot(data = ggdata_alveolar_endo, aes(x = timepoint, y = velocity_length, color = group),
                     width = 0.5, position = position_dodge2(preserve = "single", padding = 0.1)) +
        scale_color_manual(guide = guide_legend(reverse = FALSE),
                           values = c("#ff7f0e", # Dark orange
                                      "#ffbb78" # Light orange
                           )) +
        new_scale_color() +
        geom_line(data = alveolar_velocity_summary_meso,
                  aes(x = timepoint, y = median_velocity, group = group, color = group),
                  position = position_dodge(width = 0.5)) +
        geom_boxplot(data = ggdata_alveolar_meso, aes(x = timepoint, y = velocity_length, color = group),
                     width = 0.5, position = position_dodge2(preserve = "single", padding = 0.1)) +
        scale_color_manual(guide = guide_legend(reverse = FALSE),
                           values = c("#d62728", # Dark red
                                      "#ff9896" # Light red
                           )) +
        prism_theme() +
        theme(aspect.ratio = 0.4,
              panel.grid.minor.y = element_blank(),
              panel.grid.major.y = element_blank(),
              panel.grid.minor.x = element_blank(),
              panel.grid.major.x = element_blank(),
              legend.text = element_text(size = 12),
              legend.title = element_text(size = 12)
        ) +
        ylab("RNA Velocity Length") +
        labs(color = "Cell type") +

        ylim(5,25)
rna_total_velocity


all_alveolar_velocity <- rbind(ggdata_alveolar_epi, ggdata_alveolar_endo, ggdata_alveolar_meso)
all_summary_velocity <- rbind(alveolar_velocity_summary_epi, alveolar_velocity_summary_endo, alveolar_velocity_summary_meso)

rna_total_velocity <- ggplot(all_alveolar_velocity, aes(x = timepoint, y = velocity_length, color = group)) +
        geom_line(data = all_summary_velocity,
                  aes(x = timepoint, y = median_velocity, group = group, color = group),
                  position = position_dodge(width = 0.5)) +
        geom_boxplot(width = 0.5) +
        prism_theme() +
        theme(aspect.ratio = 0.4,
              panel.grid.minor.y = element_blank(),
              panel.grid.major.y = element_blank(),
              panel.grid.minor.x = element_blank(),
              panel.grid.major.x = element_blank(),
              legend.text = element_text(size = 12),
              legend.title = element_text(size = 12)
        ) +
        ylab("RNA Velocity Length") +
        labs(color = "Cell type") +
        scale_color_brewer(guide = guide_legend(reverse = TRUE), palette="Dark2") +
        ylim(5,25) +
        facet_grid(rows = vars(macro_celltype))
rna_total_velocity
```

```{r}
ggdata_meso$macro_celltype <- "Mesenchyme"
ggdata_endo$macro_celltype <- "Endothelium"
ggdata_epi$macro_celltype <- "Epithelium"

ggdata_all <- rbind(ggdata_meso, ggdata_endo, ggdata_epi)
velocity_summary <- ggdata_all %>% group_by(macro_celltype,timepoint) %>% summarise(mean_velocity=mean(velocity_length),
                                                                                    median_velocity=median(velocity_length))
velocity_summary$timepoint <- ordered(as.factor(velocity_summary$timepoint), c("E12", "E15", "E18", "P0", "P3", "P5", "P7", "P14"))

rna_total_velocity <- ggplot(ggdata_all, aes(x = timepoint, y = velocity_length, color = macro_celltype)) +
        geom_line(data = velocity_summary,
                  aes(x = timepoint, y = median_velocity, group = macro_celltype, color = macro_celltype),
                  position = position_dodge(width = 0.5)) +
        geom_boxplot() +
        prism_theme() +
        theme(aspect.ratio = 0.4,
              panel.grid.minor.y = element_blank(),
              panel.grid.major.y = element_blank(),
              panel.grid.minor.x = element_blank(),
              panel.grid.major.x = element_blank(),
              legend.text = element_text(size = 12),
              legend.title = element_text(size = 12)
        ) +
        ylab("RNA Velocity Length") +
        labs(color = "Cell type") +
        scale_color_manual(guide = guide_legend(reverse=TRUE),
                             values = c("#ff7f0e", # Orange - Endo
                                        "#1f77b4", # Blue - Epi
                                        "#d62728")) # Red - Meso
        scale_color_brewer(guide = guide_legend(reverse = TRUE), palette="Dark2")
rna_total_velocity

pdf("./figures/all/rna_velocity.pdf", width = 10, height = 4)
rna_total_velocity
dev.off()

```


```{r}
to_term <- cellrank_out$obsm$to_terminal_states

colnames(to_term) <- cellrank_out$uns$to_terminal_states_names
head(to_term)
a <- 1
```

```{r}
# De-duplicate. Other 'lineages' may be of interset later, but aren't a good broad overview.
to_term_dedup <- to_term[,c(10)]

to_term <- cbind(to_term_dedup,
                 rowSums(to_term[,c(1, 5)]), # Pericyte
                 rowSums(to_term[,c(2, 9)]), # Myofibroblast
                 rowSums(to_term[,c(3, 4)]), # Prenatal myofibroblast
                 rowSums(to_term[,c(6, 7, 8)]) # Wnt2+
)
colnames(to_term) <- c("Adventitial fibroblast",
                       "Pericyte",
                       "Myofibroblast",
                       "Proliferating Myofibroblast",
                       "*Wnt2*+ FB"
)

to_term <- as.data.frame(to_term)
to_term$timepoint <- ordered(as.factor(cellrank_out$obs$timepoint), c("E12", "E15", "E18", "P0", "P3", "P5", "P7", "P14"))

```

```{r}
prism_theme <- function(){
  theme_grey() %+replace%
    theme(panel.border = element_blank(),
          panel.background = element_blank(),
          panel.grid.major = element_line(),
          panel.grid.minor = element_blank(),
          legend.key=element_blank(),
          axis.line.x = element_line(size = 0.5, linetype = "solid", colour = "black"),
          axis.line.y = element_line(size = 0.5, linetype = "solid", colour = "black"),
          axis.text.x = element_text(size = 14, angle = 45, hjust = 1, vjust = 0.95),
          axis.text.y = element_text(size = 14),
          axis.ticks = element_line(size = 0.5),
          axis.ticks.length = unit(0.25, "cm"),
          axis.title.y = element_text(size = 16, vjust = 4, angle = 90),
          axis.title.x = element_blank(),
          plot.margin = margin(t = 5, r = 5, b = 5, l = 20),
          legend.text = element_text(size = 14),
          legend.key.size = unit(2,"line"),
          legend.title = element_blank())
}

```


```{r}

summary_stats <- melt(to_term[cellrank_out$obs$cell_subtype == "Prenatal Wnt2+",]) %>% group_by(variable) %>% summarize(mean = mean(value) * 100,
                                                                                                              median = median(value) * 100,
                                                                                                              sd = sd(value) * 100,
                                                                                                              sem = (sd(value) / sqrt(length(value))) * 100,
                                                                                                              q1 = quantile(value, 1/4) * 100,
                                                                                                              q2 = quantile(value, 3/4) * 100,
                                                                                                              #ci1 = get_lower_ci(value) * 100,
                                                                                                              #ci2 = get_upper_ci(value) * 100
)

aspect_ratio <- 1.4 # other charts are 1.6


to_term_long <- melt(to_term[cellrank_out$obs$cell_subtype == "Prenatal Wnt2+",])
to_term_long$value <- to_term_long$value * 100
to_term_long_above_zero <- to_term_long[to_term_long$value > 1,]


get_early_pct <- function(data, summary_stats, cell_group){
  timepoints <- data$obs$timepoint[data$obs$cell_subtype == cell_group]
  early <- sum(timepoints %in% c("E12", "E15", "E18")) * 100 / length(timepoints)
  return(early * summary_stats[summary_stats$variable == cell_group, "median"] / 100) # scale vals to max bar
}

for (type in unique(summary_stats$variable)){
  summary_stats[summary_stats$variable == type, "early"] <- get_early_pct(cellrank_out, summary_stats, type)
}


transitional_jitter_and_bar <- ggplot() +
        geom_col(data = summary_stats, aes(y = median, x = variable), color = "black", fill = "white") +
        #geom_col(data = summary_stats, aes(x = variable, y = early), fill = "#CDCDCD", width = 0.85) + # color early here, overlay on the other line
        geom_errorbar(data = summary_stats, aes(y = median, x = variable, ymin = q1, ymax = q2), width = 0.2) +
        #geom_boxplot(data = to_term_long, aes(y = value, x = variable), outlier.shape = NA, lwd=0.25) +
        #ggbeeswarm::geom_quasirandom(data = to_term_long, aes(y = value, x = variable), size = 0.8, shape = 1, alpha = 0.6) +
        ggtitle("Fate of<br>proliferating *Wnt2*+ FB") +
        prism_theme() +
        theme(aspect.ratio = aspect_ratio,
              plot.title = element_markdown(size = 14),
              axis.text.x = element_markdown(size = 12)
        ) +
        ylab("Transition probability (%)")
transitional_jitter_and_bar

pdf("./figures/meso/fate_prenatal_wnt2.pdf", height = 5, width = 4)
transitional_jitter_and_bar
dev.off()

tiff("./figures/meso/fate_prenatal_wnt2.tiff", height = 5, width = 4, unit = "in", res = 600, compression = "lzw")
transitional_jitter_and_bar
dev.off()
```

```{r}

summary_stats <- melt(to_term[cellrank_out$obs$cell_subtype == "Prenatal Myofibroblast",]) %>% group_by(variable) %>% summarize(mean = mean(value) * 100,
                                                                                                                        median = median(value) * 100,
                                                                                                                        sd = sd(value) * 100,
                                                                                                                        sem = (sd(value) / sqrt(length(value))) * 100,
                                                                                                                        q1 = quantile(value, 1/4) * 100,
                                                                                                                        q2 = quantile(value, 3/4) * 100,
                                                                                                                        #ci1 = get_lower_ci(value) * 100,
                                                                                                                        #ci2 = get_upper_ci(value) * 100
)

aspect_ratio <- 1.4 # other charts are 1.6

to_term_long <- melt(to_term[cellrank_out$obs$cell_subtype == "Prenatal Myofibroblast",])
to_term_long$value <- to_term_long$value * 100
to_term_long_above_zero <- to_term_long[to_term_long$value > 1,]


get_early_pct <- function(data, summary_stats, cell_group){
  timepoints <- data$obs$timepoint[data$obs$cell_subtype == cell_group]
  early <- sum(timepoints %in% c("E12", "E15", "E18")) * 100 / length(timepoints)
  return(early * summary_stats[summary_stats$variable == cell_group, "median"] / 100) # scale vals to max bar
}

for (type in unique(summary_stats$variable)){
  summary_stats[summary_stats$variable == type, "early"] <- get_early_pct(cellrank_out, summary_stats, type)
}


prenatal_myo_jitter_and_bar <- ggplot() +
        geom_col(data = summary_stats, aes(y = median, x = variable), color = "black", fill = "white") +
        #geom_col(data = summary_stats, aes(x = variable, y = early), fill = "#CDCDCD", width = 0.85) + # color early here, overlay on the other line
        geom_errorbar(data = summary_stats, aes(y = median, x = variable, ymin = q1, ymax = q2), width = 0.2) +
        #geom_boxplot(data = to_term_long, aes(y = value, x = variable), outlier.shape = NA, lwd=0.25) +
        #ggbeeswarm::geom_quasirandom(data = to_term_long, aes(y = value, x = variable), size = 0.8, shape = 1, alpha = 0.6) +
        ggtitle("Fate of<br>proliferating myofibroblasts") +
        prism_theme() +
  theme(aspect.ratio = aspect_ratio,
        plot.title = element_markdown(size = 14),
        axis.text.x = element_markdown(size = 12)
  ) +
        ylab("Transition probability (%)")
prenatal_myo_jitter_and_bar



pdf("./figures/meso/fate_prenatal_myo.pdf", height = 5, width = 4)
prenatal_myo_jitter_and_bar
dev.off()


tiff("./figures/meso/fate_prenatal_myo.tiff", height = 5, width = 4, unit = "in", res = 600, compression = "lzw")
prenatal_myo_jitter_and_bar
dev.off()
```

```{r}

from_initial <- cellrank_out$obsm$from_initial_states #absorbtion from X
colnames(from_initial) <- cellrank_out$uns$from_initial_states_names
head(from_initial)
```

```{r}
# De-duplicate. Other 'lineages' may be of interset later, but aren't a good broad overview.
from_initial_dedup <- from_initial[,c(3, 5, 7, 8, 9)]

from_initial <- cbind(from_initial_dedup,
                 rowSums(from_initial[,c(2, 4)]), # Prenatal Myofibroblast
                 rowSums(from_initial[,c(1, 6)]) # Pericyte

)
colnames(from_initial) <- c("Smooth muscle",
                            "Mesothelium",
                            "*Wnt2*+ FB",
                            "Proliferating *Wnt2*+ FB",
                            "Myofibroblast",
                            "Proliferating myofibroblast",
                            "Pericyte"
)
```

```{r}
# Combine similar terminal types
#from_initial_no_T2 <- from_initial[,c(1,2,3,5)]

#from_initial <- cbind(from_initial_no_T2, rowSums(from_initial[,c(4,6,7)])) # Merge the Type II fates
#colnames(from_initial) <- c(colnames(from_initial_no_T2), "Type II")
from_initial <- as.data.frame(from_initial)
from_initial$timepoint <- ordered(as.factor(cellrank_out$obs$timepoint), c("E12", "E15", "E18", "P0", "P3", "P5", "P7", "P14"))

head(from_initial[cellrank_out$obs$cell_subtype == "Prenatal Wnt2+",])


to_wnt2_plot <- ggplot(melt(from_initial[cellrank_out$obs$cell_subtype == "Prenatal Wnt2+",]), aes(x = value, color = variable, fill = variable)) +
        geom_density(alpha = 0.3) +
        scale_x_continuous(limits = c(0.05,1)) +
        ggtitle("Fate probability towards 'Prenatal Wnt2+' cells")

to_wnt2_plot

```

```{r}
summary_stats <- melt(from_initial[cellrank_out$obs$cell_subtype == "Wnt2+",]) %>% group_by(variable) %>% summarize(mean = mean(value) * 100,
                                                                                                                    median = median(value) * 100,
                                                                                                                    sd = sd(value) * 100,
                                                                                                                    sem = (sd(value) / sqrt(length(value))) * 100,
                                                                                                                    q1 = quantile(value, 1/4) * 100,
                                                                                                                    q2 = quantile(value, 3/4) * 100,
)

#levels(summary_stats$variable)[2] <- "Proliferating miEC"

#median(check_means[check_means > 0])


to_wnt2_long <- melt(from_initial[cellrank_out$obs$cell_subtype == "Wnt2+",])
to_wnt2_long$value <- to_wnt2_long$value * 100
to_wnt2_long <- to_wnt2_long[to_wnt2_long$value > 1,]

#levels(from_initial_long$variable)[2] <- "Proliferating miEC"


transitional_barplot <- ggplot() +
  geom_col(data = summary_stats, aes(y = median, x = variable), color = "black", fill = "white") +

  #geom_col(data = summary_stats, aes(x = variable, y = early), fill = "#CDCDCD", width = 0.84) + # color early here, overlay on the other line
  geom_errorbar(data = summary_stats, aes(y = median, x = variable, ymin = q1, ymax = q2), width = 0.6) +
  #geom_boxplot(data = from_initial_long, aes(y = value, x = variable), outlier.shape = NA, lwd=0.25) +
  #ggbeeswarm::geom_quasirandom(data = from_initial_long, aes(y = value, x = variable), size = 0.8, shape = 1, alpha = 0.6) +
  ggtitle("Source of *Wnt2*+ FB") +
  prism_theme() +
  theme(aspect.ratio = 1.6,
        plot.title = element_markdown(size = 14),
        axis.text.x = element_markdown(size = 14)
  ) +
  ylab("Transition probability (%)")

transitional_barplot


pdf("./figures/meso/to_wnt2_probability.pdf", height = 5, width = 3)
transitional_barplot
dev.off()
```

```{r}
summary_stats <- melt(from_initial[cellrank_out$obs$cell_subtype == "Myofibroblast",]) %>% group_by(variable) %>% summarize(mean = mean(value) * 100,
                                                                                                                             median = median(value) * 100,
                                                                                                                             sd = sd(value) * 100,
                                                                                                                             sem = (sd(value) / sqrt(length(value))) * 100,
                                                                                                                             q1 = quantile(value, 1/4) * 100,
                                                                                                                             q2 = quantile(value, 3/4) * 100,
)

#levels(summary_stats$variable)[2] <- "Proliferating miEC"

#median(check_means[check_means > 0])


to_wnt2_long <- melt(from_initial[cellrank_out$obs$cell_subtype == "Myofibroblast",])
to_wnt2_long$value <- to_wnt2_long$value * 100
to_wnt2_long <- to_wnt2_long[to_wnt2_long$value > 1,]

#levels(from_initial_long$variable)[2] <- "Proliferating miEC"


transitional_barplot <- ggplot() +
  geom_col(data = summary_stats, aes(y = median, x = variable), color = "black", fill = "white") +

  #geom_col(data = summary_stats, aes(x = variable, y = early), fill = "#CDCDCD", width = 0.84) + # color early here, overlay on the other line
  geom_errorbar(data = summary_stats, aes(y = median, x = variable, ymin = q1, ymax = q2), width = 0.6) +
  #geom_boxplot(data = from_initial_long, aes(y = value, x = variable), outlier.shape = NA, lwd=0.25) +
  #ggbeeswarm::geom_quasirandom(data = from_initial_long, aes(y = value, x = variable), size = 0.8, shape = 1, alpha = 0.6) +
  ggtitle("Source of myofibroblast") +
  prism_theme() +
  theme(aspect.ratio = 1.6,
        plot.title = element_markdown(size = 14),
        axis.text.x = element_markdown(size = 14)
  ) +
  ylab("Transition probability (%)")

transitional_barplot


pdf("./figures/meso/to_myo_probability.pdf", height = 5, width = 3)
transitional_barplot
dev.off()
```

