---
title: "Plottings outputs of the cellrank analysis"
author: Nick Negretti
date: 12/07/20
output:
  html_document:
    df_print: paged
    toc: true
    toc_float:
      toc_collapsed: false
    toc_depth: 3
    number_sections: false
    theme: lumen
---

```{css toc-content, echo = FALSE}

.main-container {
    margin-left: 20px;
}
.tocify-extend-page {
  height: 0 !important;
}
```
# Plot cellrank outputs of the lung epithelium

## Load libraries and helper functions
```{r, results="hide", message = FALSE}
setwd("~/postdoc/code/devo_scseq")

source("./helper_functions/libraries.R")

opts_knit$set(root.dir = getwd())

source("./helper_functions/trajectory.R")

source("./helper_functions/cluster.R")
source("./helper_functions/colors.R")
source("./helper_functions/brackets.R")
source("./helper_functions/heatmaps.R")
set.seed(42) # For reproducability

N_WORKERS <- 3
options(future.globals.maxSize=2048*1024^2)
plan("multiprocess", workers = N_WORKERS)
```
## Load data from merge and clean pipeline
```{r}
cellrank_out <- anndata::read_h5ad("./velocity/epi/only_metadata.h5ad")
cellrank_out
```



```{r}
cellrank_out$uns$initial_states_names
```

```{r}
ggdata_epi <- data.frame(x = cellrank_out$obsm$X_umap[,1],
                     y = cellrank_out$obsm$X_umap[,2],
                     velocity_length = cellrank_out$obs$velocity_length,
                     group = as.character(cellrank_out$obs$cell_subtype),
                     timepoint = as.character(cellrank_out$obs$timepoint))
head(ggdata_epi)
colnames(ggdata_epi) <- c("x", "y", "velocity_length", "group", "timepoint")
mean(ggdata_epi$velocity_length)

ggplot(ggdata_epi %>% arrange(velocity_length), aes(x = x, y = y, color = velocity_length)) + geom_point() + umap_theme() + theme(aspect.ratio = 1) + scale_color_viridis()

```


```{r}
epi_ms <- Matrix::readMM("./velocity/epi/epi_expression_Ms.mtx.gz")
```


```{r}
gene <- "Wnt7b"
include_celltypes <- c("AT1", "AT2", "Primordial", "Transitional")
exp_over_time <- data.frame(expression = epi_ms[,colnames(cellrank_out) == gene],
                            Cluster = cellrank_out$obs$cell_subtype,
                            latent_time = cellrank_out$obs$latent_time
)

unique(exp_over_time$Cluster)

levels(exp_over_time$Cluster)[levels(exp_over_time$Cluster) == "Type I"] <- "AT1"
levels(exp_over_time$Cluster)[levels(exp_over_time$Cluster) == "Type II"] <- "AT2"



exp_over_time$Cluster <- ordered(as.factor(exp_over_time$Cluster), c("Primordial", "Transitional", "AT1", "AT2", "Cilliated", "Secretory", "Neuroendocrine"))

exp_over_time <- exp_over_time[exp_over_time$Cluster %in% include_celltypes,]

test_exp <- ggplot(exp_over_time, aes(y = expression, x = latent_time, color = Cluster)) +
        geom_point(alpha = 0.5) +
        scale_color_manual(aesthetics = c("color", "fill"), values= color_category_20, guide = guide_legend(override.aes = list(size=3), order = 1)) +
        theme(legend.key = element_blank(),
              legend.text = element_markdown(size=14),
              legend.title = element_markdown(size=16),
              #axis.text.x  = element_text(size=14),
              axis.text.x = element_blank(),
              axis.ticks.x = element_blank(),
              axis.text.y = element_text(size=14),
              axis.title.x = element_text(size=14, vjust = -1),
              axis.title.y = element_text(size=14),
              panel.grid.major = element_blank(),
              panel.grid.minor = element_blank(),
              panel.background = element_rect(fill = "white", color = "black"),
              aspect.ratio = 0.8,
              plot.title = element_markdown(size = 16)
        ) +
        scale_x_continuous(breaks = c(0,1)) +
        ylab("Expression") +
        xlab("Latent time") +
        ggtitle(paste0("*", gene, "*"))

test_exp

```


```{r}
gene <- "Hopx"
include_celltypes <- c("AT1", "AT2", "Primordial", "Transitional")
exp_over_time <- data.frame(expression = epi_ms[,colnames(cellrank_out) == gene],
                            Cluster = cellrank_out$obs$cell_subtype,
                            latent_time = cellrank_out$obs$latent_time
)

unique(exp_over_time$Cluster)

levels(exp_over_time$Cluster)[levels(exp_over_time$Cluster) == "Type I"] <- "AT1"
levels(exp_over_time$Cluster)[levels(exp_over_time$Cluster) == "Type II"] <- "AT2"



exp_over_time$Cluster <- ordered(as.factor(exp_over_time$Cluster), c("Primordial", "Transitional", "AT1", "AT2", "Cilliated", "Secretory", "Neuroendocrine"))

exp_over_time <- exp_over_time[exp_over_time$Cluster %in% include_celltypes,]

hopx_exp <- ggplot(exp_over_time, aes(y = expression, x = latent_time, color = Cluster)) +
    geom_point(alpha = 0.5) +
    scale_color_manual(aesthetics = c("color", "fill"), values= color_category_20, guide = guide_legend(override.aes = list(size=3), order = 1)) +
    theme(legend.key = element_blank(),
        legend.text = element_markdown(size=14),
        legend.title = element_markdown(size=16),
        #axis.text.x  = element_text(size=14),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        axis.text.y = element_text(size=14),
        axis.title.x = element_text(size=14, vjust = -1),
        axis.title.y = element_text(size=14),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.background = element_rect(fill = "white", color = "black"),
        aspect.ratio = 0.8,
        plot.title = element_markdown(size = 16)
    ) +
    scale_x_continuous(breaks = c(0,1)) +
    ylab("Expression") +
    xlab("Latent time") +
    ggtitle(paste0("*", gene, "*"))

hopx_exp

```

```{r}
gene <- "Sftpc"
include_celltypes <- c("AT1", "AT2", "Primordial", "Transitional")
exp_over_time <- data.frame(expression = epi_ms[,colnames(cellrank_out) == gene],
                            Cluster = cellrank_out$obs$cell_subtype,
                            latent_time = cellrank_out$obs$latent_time
)

unique(exp_over_time$Cluster)

levels(exp_over_time$Cluster)[levels(exp_over_time$Cluster) == "Type I"] <- "AT1"
levels(exp_over_time$Cluster)[levels(exp_over_time$Cluster) == "Type II"] <- "AT2"



exp_over_time$Cluster <- ordered(as.factor(exp_over_time$Cluster), c("Primordial", "Transitional", "AT1", "AT2", "Cilliated", "Secretory", "Neuroendocrine"))

exp_over_time <- exp_over_time[exp_over_time$Cluster %in% include_celltypes,]

sftpc_exp <- ggplot(exp_over_time, aes(y = expression, x = latent_time, color = Cluster)) +
        geom_point(alpha = 0.5) +
        scale_color_manual(aesthetics = c("color", "fill"), values= color_category_20, guide = guide_legend(override.aes = list(size=3), order = 1)) +
        theme(legend.key = element_blank(),
              legend.text = element_markdown(size=14),
              legend.title = element_markdown(size=16),
              #axis.text.x  = element_text(size=14),
              axis.text.x = element_blank(),
              axis.ticks.x = element_blank(),
              axis.text.y = element_text(size=14),
              axis.title.x = element_text(size=14, vjust = -1),
              axis.title.y = element_text(size=14),
              panel.grid.major = element_blank(),
              panel.grid.minor = element_blank(),
              panel.background = element_rect(fill = "white", color = "black"),
              aspect.ratio = 0.8,
              plot.title = element_markdown(size = 16)
        ) +
        scale_x_continuous(breaks = c(0,1)) +
        ylab("Expression") +
        xlab("Latent time") +
        ggtitle(paste0("*", gene, "*"))

sftpc_exp

```

```{r}
gene <- "Cdkn1a"
include_celltypes <- c("AT1", "AT2", "Primordial", "Transitional")
exp_over_time <- data.frame(expression = epi_ms[,colnames(cellrank_out) == gene],
                            Cluster = cellrank_out$obs$cell_subtype,
                            latent_time = cellrank_out$obs$latent_time
)

unique(exp_over_time$Cluster)

levels(exp_over_time$Cluster)[levels(exp_over_time$Cluster) == "Type I"] <- "AT1"
levels(exp_over_time$Cluster)[levels(exp_over_time$Cluster) == "Type II"] <- "AT2"



exp_over_time$Cluster <- ordered(as.factor(exp_over_time$Cluster), c("Primordial", "Transitional", "AT1", "AT2", "Cilliated", "Secretory", "Neuroendocrine"))

exp_over_time <- exp_over_time[exp_over_time$Cluster %in% include_celltypes,]

cdkn1a_exp <- ggplot(exp_over_time, aes(y = expression, x = latent_time, color = Cluster)) +
        geom_point(alpha = 0.5) +
        scale_color_manual(aesthetics = c("color", "fill"), values= color_category_20, guide = guide_legend(override.aes = list(size=3), order = 1)) +
        theme(legend.key = element_blank(),
              legend.text = element_markdown(size=14),
              legend.title = element_markdown(size=16),
              #axis.text.x  = element_text(size=14),
              axis.text.x = element_blank(),
              axis.ticks.x = element_blank(),
              axis.text.y = element_text(size=14),
              axis.title.x = element_text(size=14, vjust = -1),
              axis.title.y = element_text(size=14),
              panel.grid.major = element_blank(),
              panel.grid.minor = element_blank(),
              panel.background = element_rect(fill = "white", color = "black"),
              aspect.ratio = 0.8,
              plot.title = element_markdown(size = 16)
        ) +
        scale_x_continuous(breaks = c(0,1)) +
        ylab("Expression") +
        xlab("Latent time") +
        ggtitle(paste0("*", gene, "*"))

cdkn1a_exp

```


```{r}
#tiff("./figures/epi/latent_time/sftpc_hopx_cdkn1a.tiff", width = 20, height =4.5, units = "in", res = 600, compression = "lzw", bg = "transparent")
#hopx_exp + sftpc_exp +  cdkn1a_exp + plot_layout(ncol = 3, nrow = 1, guides = "collect")
#dev.off()

tiff("./figures/epi/latent_time/sftpc_hopx.tiff", width = 13, height =4.5, units = "in", res = 600, compression = "lzw", bg = "transparent")
hopx_exp + sftpc_exp +  plot_layout(ncol = 2, nrow = 1, guides = "collect")
dev.off()


tiff("./figures/epi/latent_time/cdkn1a.tiff", width = 6, height =4.5, units = "in", res = 600, compression = "lzw", bg = "transparent")
cdkn1a_exp
dev.off()


```

```{r}
gene <- "Fbln5"
include_celltypes <- c("AT1", "AT2", "Primordial", "Transitional")
exp_over_time <- data.frame(expression = epi_ms[,colnames(cellrank_out) == gene],
                            Cluster = cellrank_out$obs$cell_subtype,
                            latent_time = cellrank_out$obs$latent_time
)

unique(exp_over_time$Cluster)

levels(exp_over_time$Cluster)[levels(exp_over_time$Cluster) == "Type I"] <- "AT1"
levels(exp_over_time$Cluster)[levels(exp_over_time$Cluster) == "Type II"] <- "AT2"



exp_over_time$Cluster <- ordered(as.factor(exp_over_time$Cluster), c("Primordial", "Transitional", "AT1", "AT2", "Cilliated", "Secretory", "Neuroendocrine"))

exp_over_time <- exp_over_time[exp_over_time$Cluster %in% include_celltypes,]

fbln5_exp <- ggplot(exp_over_time, aes(y = expression, x = latent_time, color = Cluster)) +
        geom_point(alpha = 0.5) +
        scale_color_manual(values= color_category_20, guide = guide_legend(override.aes = list(size=3), order = 1)) +
        theme(legend.key = element_blank(),
              legend.text = element_markdown(size=14),
              legend.title = element_markdown(size=16),
              #axis.text.x  = element_text(size=14),
              axis.text.x = element_blank(),
              axis.ticks.x = element_blank(),
              axis.text.y = element_text(size=14),
              axis.title.x = element_text(size=14, vjust = -1),
              axis.title.y = element_text(size=14),
              panel.grid.major = element_blank(),
              panel.grid.minor = element_blank(),
              panel.background = element_rect(fill = "white", color = "black"),
              aspect.ratio = 0.8,
              plot.title = element_markdown(size = 16)
        ) +
        scale_x_continuous(breaks = c(0,1)) +
        ylab("Expression") +
        xlab("Latent time") +
        ggtitle(paste0("*", gene, "*"))

fbln5_exp

tiff("./figures/epi/latent_time/fbln5.tiff", width = 6, height =4.5, units = "in", res = 600, compression = "lzw", bg = "transparent")
fbln5_exp
dev.off()
```


```{r}
head(colnames(cellrank_out))
```

```{r}
to_term_nomerge <- cellrank_out$obsm$to_terminal_states

colnames(to_term_nomerge) <- cellrank_out$uns$to_terminal_states_names


# Combine similar terminal types
to_term <- cbind(to_term_nomerge[,c(1,2)], rowSums(to_term_nomerge[,c(3,4)]), rowSums(to_term_nomerge[,c(5,6,8)]), rowSums(to_term_nomerge[,c(7,9)]))
colnames(to_term) <- c("Neuroendocrine", "Secretory", "Cilliated", "Type II", "Type I")
to_term <- as.data.frame(to_term)
to_term$timepoint <- ordered(as.factor(cellrank_out$obs$timepoint), c("E12", "E15", "E18", "P0", "P3", "P5", "P7", "P14"))

head(to_term[cellrank_out$obs$cell_subtype == "Transitional",])
```

```{r}
ggplot(melt(to_term[cellrank_out$obs$cell_subtype == "Type II",]), aes(x = value, color = variable, fill = variable)) +
        geom_density(alpha = 0.3) +
        scale_x_continuous(limits = c(0.1,1)) +
        facet_grid(vars(timepoint), scales = "free")



transitional_plot <- ggplot(melt(to_term[cellrank_out$obs$cell_subtype == "Transitional",]), aes(x = value, color = variable, fill = variable)) +
  geom_density(alpha = 0.3) +
  scale_x_continuous(limits = c(0.1,1)) +
        ggtitle("Fate probability of 'transitional' cells")

T1_plot <- ggplot(melt(to_term[cellrank_out$obs$cell_subtype == "Type I",]), aes(x = value, color = variable, fill = variable)) +
  geom_density(alpha = 0.3) +
  scale_x_continuous(limits = c(0.1,1)) +
  ggtitle("Fate probability of 'Type I' cells")

T2_plot <- ggplot(melt(to_term[cellrank_out$obs$cell_subtype == "Type II",]), aes(x = value, color = variable, fill = variable)) +
  geom_density(alpha = 0.3) +
  scale_x_continuous(limits = c(0.1,1)) +
  ggtitle("Fate probability of 'Type II' cells")

primordial_plot <- ggplot(melt(to_term[cellrank_out$obs$cell_subtype == "Primordial",]), aes(x = value, color = variable, fill = variable)) +
  geom_density(alpha = 0.3) +
  scale_x_continuous(limits = c(0.1,1)) +
  ggtitle("Fate probability of 'Primordial' cells")

secretory_plot <- ggplot(melt(to_term[cellrank_out$obs$cell_subtype == "Secretory",]), aes(x = value, color = variable, fill = variable)) +
  geom_density(alpha = 0.3) +
  scale_x_continuous(limits = c(0.1,1)) +
  ggtitle("Fate probability of 'Secretory' cells")

transitional_plot + T1_plot + T2_plot + primordial_plot + secretory_plot + patchwork::plot_layout(ncol = 1)

```

```{r}
prism_theme <- function(){
  theme_grey() %+replace%
    theme(panel.border = element_blank(),
          panel.background = element_blank(),
          panel.grid.major = element_line(),
          panel.grid.minor = element_blank(),
          legend.key=element_blank(),
          axis.line.x = element_line(size = 0.5, linetype = "solid", colour = "black"),
          axis.line.y = element_line(size = 0.5, linetype = "solid", colour = "black"),
          axis.text.x = element_text(size = 14, angle = 45, hjust = 1, vjust = 0.95),
          axis.text.y = element_text(size = 14),
          axis.ticks = element_line(size = 0.5),
          axis.ticks.length = unit(0.25, "cm"),
          axis.title.y = element_text(size = 16, vjust = 4, angle = 90),
          axis.title.x = element_blank(),
          plot.margin = margin(t = 5, r = 5, b = 5, l = 20),
          legend.text = element_text(size = 14),
          legend.key.size = unit(2,"line"),
          legend.title = element_blank())
}

```

```{r}


colnames(to_term)[4:5] <- c("AT2", "AT1")

summary_stats <- melt(to_term[cellrank_out$obs$cell_subtype == "Transitional",]) %>% group_by(variable) %>% summarize(mean = mean(value) * 100,
                                                                                                                      median = median(value) * 100,
                                                                                                                      sd = sd(value) * 100,
                                                                                                                      sem = (sd(value) / sqrt(length(value))) * 100,
                                                                                                                      q1 = quantile(value, 1/4) * 100,
                                                                                                                      q2 = quantile(value, 3/4) * 100,
                                                                                                                      ci1 = get_lower_ci(value) * 100,
                                                                                                                      ci2 = get_upper_ci(value) * 100)

to_term_long <- melt(to_term[cellrank_out$obs$cell_subtype == "Transitional",])
to_term_long$value <- to_term_long$value * 100
to_term_long_above_zero <- to_term_long[to_term_long$value > 1,]

transitional_jitter <- ggplot(to_term_long, aes(y = value, x = variable)) +
        ggbeeswarm::geom_quasirandom(size = 0.8, shape = 1, alpha = 0.6, bandwidth = 1) +
        ggtitle("Fate of 'transitional' cells") +
        prism_theme() +
        theme(aspect.ratio = 1.6) +
        ylab("Transition probability (%)")

transitional_violin <- ggplot(to_term_long_above_zero, aes(y = value, x = variable)) +
        geom_violin() +
        ggtitle("Fate of 'transitional' cells") +
        prism_theme() +
        theme(aspect.ratio = 1.6) +
        ylab("Transition probability (%)")

transitional_barplot <- ggplot(summary_stats, aes(y = median, x = variable)) +
  geom_col() +
  geom_errorbar(aes(ymin = q1, ymax = q2), width = 0.2) +
  ggtitle("Fate of 'transitional' cells") +
  prism_theme() +
  theme(aspect.ratio = 1.6) +
  ylab("Transition probability (%)")

get_early_pct <- function(data, summary_stats, cell_group){
  timepoints <- data$obs$timepoint[data$obs$cell_subtype == cell_group]
  early <- sum(timepoints %in% c("E12", "E15", "E18")) * 100 / length(timepoints)
  return(early * summary_stats[summary_stats$variable == cell_group, "median"] / 100) # scale vals to max bar
}

for (type in unique(summary_stats$variable)){
  summary_stats[summary_stats$variable == type, "early"] <- get_early_pct(cellrank_out, summary_stats, type)
}

summary_stats$variable <- ordered(summary_stats$variable, levels(summary_stats$variable)[order(as.character(levels(summary_stats$variable)))])
transitional_jitter_and_bar <- ggplot() +
        geom_col(data = summary_stats, aes(y = median, x = variable), color = "black", fill = "white") +
        geom_col(data = summary_stats, aes(x = variable, y = early), fill = "#CDCDCD", width = 0.85) + # color early here, overlay on the other line
        geom_errorbar(data = summary_stats, aes(y = median, x = variable, ymin = q1, ymax = q2), width = 0.6) +
        #geom_boxplot(data = to_term_long, aes(y = value, x = variable), outlier.shape = NA, lwd=0.25) +
        #ggbeeswarm::geom_quasirandom(data = to_term_long, aes(y = value, x = variable), size = 0.8, shape = 1, alpha = 0.6) +
        ggtitle("Fate of transitional cells") +
        prism_theme() +
        theme(aspect.ratio = 1.6) +
        ylab("Transition probability (%)")

transitional_jitter_and_bar

transitional_violin + transitional_jitter + transitional_barplot + transitional_jitter_and_bar + plot_layout(nrow = 1)

pdf("./figures/epi/from_transitional_probability.pdf", height = 5.3, width = 3.5)
transitional_jitter_and_bar
dev.off()
```
```{r}
summary_stats <- melt(to_term[cellrank_out$obs$cell_subtype == "Type II",]) %>% group_by(variable) %>% summarize(mean = mean(value) * 100,
                                                                                                                      median = median(value) * 100,
                                                                                                                      sd = sd(value) * 100,
                                                                                                                      sem = (sd(value) / sqrt(length(value))) * 100,
                                                                                                                      q1 = quantile(value, 1/4) * 100,
                                                                                                                      q2 = quantile(value, 3/4) * 100
                                                                                                                      #ci1 = get_lower_ci(value) * 100,
                                                                                                                      #ci2 = get_upper_ci(value) * 100
                                                                                                                      )


get_early_pct <- function(data, summary_stats, cell_group){
  timepoints <- data$obs$timepoint[data$obs$cell_subtype == cell_group]
  early <- sum(timepoints %in% c("E12", "E15", "E18")) * 100 / length(timepoints)
  return(early * summary_stats[summary_stats$variable == cell_group, "median"] / 100) # scale vals to max bar
}

for (type in unique(summary_stats$variable)){
  summary_stats[summary_stats$variable == type, "early"] <- get_early_pct(cellrank_out, summary_stats, type)
}


to_term_long <- melt(to_term[cellrank_out$obs$cell_subtype == "Type II",])
to_term_long$value <- to_term_long$value * 100
to_term_long_above_zero <- to_term_long[to_term_long$value > 1,]

at2_1_transitional_jitter_and_bar <- ggplot() +
        geom_col(data = summary_stats, aes(y = median, x = variable), color = "black", fill = "white") +
        geom_col(data = summary_stats, aes(x = variable, y = early), fill = "#CDCDCD", width = 0.85) + # color early here, overlay on the other line
        geom_errorbar(data = summary_stats, aes(y = median, x = variable, ymin = q1, ymax = q2), width = 0.6) +
        #geom_boxplot(data = to_term_long, aes(y = value, x = variable), outlier.shape = NA, lwd=0.25) +
        #ggbeeswarm::geom_quasirandom(data = to_term_long, aes(y = value, x = variable), size = 0.8, shape = 1, alpha = 0.6) +
        ggtitle("Fate of AT2 cells") +
        prism_theme() +
        theme(aspect.ratio = 1.6,
              plot.title = element_markdown(size = 14),
              axis.text.x = element_markdown(size = 14)) +
        ylab("Transition probability (%)")

at2_1_transitional_jitter_and_bar

pdf("./figures/epi/fate_AT2.pdf", height = 5.3, width = 3.5)
at2_1_transitional_jitter_and_bar
dev.off()

```


```{r}
from_initial <- cellrank_out$obsm$from_initial_states

colnames(from_initial) <- cellrank_out$uns$from_initial_states_names

head(from_initial)
# Combine similar terminal types

from_initial <- cbind(from_initial[,c(1:3, 5)], rowSums(from_initial[,c(4,6,7)])) # Merge the Type II fates
colnames(from_initial) <- c(colnames(from_initial)[c(1:4)], "Type II")
from_initial <- as.data.frame(from_initial)
from_initial$timepoint <- ordered(as.factor(cellrank_out$obs$timepoint), c("E12", "E15", "E18", "P0", "P3", "P5", "P7", "P14"))

head(from_initial[cellrank_out$obs$cell_subtype == "Transitional",])
colnames(from_initial)[4:5] <- c("AT1", "AT2")

transitional_plot <- ggplot(melt(from_initial[cellrank_out$obs$cell_subtype == "Transitional",]), aes(x = value, color = variable, fill = variable)) +
  geom_density(alpha = 0.3) +
  scale_x_continuous(limits = c(0.05,1)) +
  ggtitle("Fate probability towards 'transitional' cells")

transitional_plot



```

```{r}

summary_stats <- melt(from_initial[cellrank_out$obs$cell_subtype == "Type II",]) %>% group_by(variable) %>% summarize(mean = mean(value) * 100,
                                                                                                                           median = median(value) * 100,
                                                                                                                           sd = sd(value) * 100,
                                                                                                                           sem = (sd(value) / sqrt(length(value))) * 100,
                                                                                                                           q1 = quantile(value, 1/4) * 100,
                                                                                                                           q2 = quantile(value, 3/4) * 100)
from_initial_long <- melt(from_initial[cellrank_out$obs$cell_subtype == "Type II",])
from_initial_long$value <- from_initial_long$value * 100
#from_initial_long_above_zero <- from_initial_long[to_term_long$value > 1,]


summary_stats$early <- 0

get_early_pct <- function(data, summary_stats, cell_group){
  timepoints <- data$obs$timepoint[data$obs$cell_subtype == cell_group]
  early <- sum(timepoints %in% c("E12", "E15", "E18")) * 100 / length(timepoints)
  return(early * summary_stats[summary_stats$variable == cell_group, "median"] / 100) # scale vals to max bar
}

for (type in unique(summary_stats$variable)){
  summary_stats[summary_stats$variable == type, "early"] <- get_early_pct(cellrank_out, summary_stats, type)
}

AT2_jitter_and_bar <- ggplot() +
        geom_col(data = summary_stats, aes(y = median, x = variable), color = "black", fill = "white") +
        geom_col(data = summary_stats, aes(x = variable, y = early), fill = "#CDCDCD", width = 0.85) + # color early here, overlay on the other line
        geom_errorbar(data = summary_stats, aes(y = median, x = variable, ymin = q1, ymax = q2), width = 0.6) +
        #geom_boxplot(data = from_initial_long, aes(y = value, x = variable), outlier.shape = NA, lwd=0.25) +
        #ggbeeswarm::geom_quasirandom(data = from_initial_long, aes(y = value, x = variable), size = 0.8, shape = 1, alpha = 0.6) +
        ggtitle("Source of AT2 cells") +
        prism_theme() +
        theme(aspect.ratio = 1.6,
              plot.title = element_markdown(size = 16),
              axis.text.x = element_markdown(size = 14)) +
        ylab("Transition probability (%)")

AT2_jitter_and_bar

pdf("./figures/epi/to_AT2.pdf", height = 5.2, width = 3.2)
AT2_jitter_and_bar
dev.off()
```
```{r}
summary_stats <- melt(from_initial[cellrank_out$obs$cell_subtype == "Type I",]) %>% group_by(variable) %>% summarize(mean = mean(value) * 100,
                                                                                                                      median = median(value) * 100,
                                                                                                                      sd = sd(value) * 100,
                                                                                                                      sem = (sd(value) / sqrt(length(value))) * 100,
                                                                                                                      q1 = quantile(value, 1/4) * 100,
                                                                                                                      q2 = quantile(value, 3/4) * 100)
from_initial_long <- melt(from_initial[cellrank_out$obs$cell_subtype == "Type I",])
from_initial_long$value <- from_initial_long$value * 100
#from_initial_long_above_zero <- from_initial_long[to_term_long$value > 1,]


summary_stats$early <- 0

get_early_pct <- function(data, summary_stats, cell_group){
  timepoints <- data$obs$timepoint[data$obs$cell_subtype == cell_group]
  early <- sum(timepoints %in% c("E12", "E15", "E18")) * 100 / length(timepoints)
  return(early * summary_stats[summary_stats$variable == cell_group, "median"] / 100) # scale vals to max bar
}

for (type in unique(summary_stats$variable)){
  summary_stats[summary_stats$variable == type, "early"] <- get_early_pct(cellrank_out, summary_stats, type)
}

AT1_jitter_and_bar <- ggplot() +
        geom_col(data = summary_stats, aes(y = median, x = variable), color = "black", fill = "white") +
        geom_col(data = summary_stats, aes(x = variable, y = early), fill = "#CDCDCD", width = 0.85) + # color early here, overlay on the other line
        geom_errorbar(data = summary_stats, aes(y = median, x = variable, ymin = q1, ymax = q2), width = 0.6) +
        #geom_boxplot(data = from_initial_long, aes(y = value, x = variable), outlier.shape = NA, lwd=0.25) +
        #ggbeeswarm::geom_quasirandom(data = from_initial_long, aes(y = value, x = variable), size = 0.8, shape = 1, alpha = 0.6) +
        ggtitle("Source of AT1 cells") +
        prism_theme() +
        theme(aspect.ratio = 1.6,
              plot.title = element_markdown(size = 16),
              axis.text.x = element_markdown(size = 14)) +
        ylab("Transition probability (%)")

AT1_jitter_and_bar

pdf("./figures/epi/to_AT1.pdf", height = 5.2, width = 3.2)
AT1_jitter_and_bar
dev.off()
```


```{r}
summary_stats <- melt(from_initial[cellrank_out$obs$cell_subtype == "Transitional",]) %>% group_by(variable) %>% summarize(mean = mean(value) * 100,
                                                                                                                     median = median(value) * 100,
                                                                                                                     sd = sd(value) * 100,
                                                                                                                     sem = (sd(value) / sqrt(length(value))) * 100,
                                                                                                                     q1 = quantile(value, 1/4) * 100,
                                                                                                                     q2 = quantile(value, 3/4) * 100)
from_initial_long <- melt(from_initial[cellrank_out$obs$cell_subtype == "Transitional",])
from_initial_long$value <- from_initial_long$value * 100
#from_initial_long_above_zero <- from_initial_long[to_term_long$value > 1,]


summary_stats$early <- 0

get_early_pct <- function(data, summary_stats, cell_group){
  timepoints <- data$obs$timepoint[data$obs$cell_subtype == cell_group]
  early <- sum(timepoints %in% c("E12", "E15", "E18")) * 100 / length(timepoints)
  return(early * summary_stats[summary_stats$variable == cell_group, "median"] / 100) # scale vals to max bar
}

for (type in unique(summary_stats$variable)){
  summary_stats[summary_stats$variable == type, "early"] <- get_early_pct(cellrank_out, summary_stats, type)
}

summary_stats$variable <- ordered(summary_stats$variable, levels(summary_stats$variable)[order(as.character(levels(summary_stats$variable)))])

to_transitional_jitter_and_bar <- ggplot() +
        geom_col(data = summary_stats, aes(y = median, x = variable), color = "black", fill = "white") +
        geom_col(data = summary_stats, aes(x = variable, y = early), fill = "#CDCDCD", width = 0.85) + # color early here, overlay on the other line
        geom_errorbar(data = summary_stats, aes(y = median, x = variable, ymin = q1, ymax = q2), width = 0.6) +
        #geom_boxplot(data = from_initial_long, aes(y = value, x = variable), outlier.shape = NA, lwd=0.25) +
        #ggbeeswarm::geom_quasirandom(data = from_initial_long, aes(y = value, x = variable), size = 0.8, shape = 1, alpha = 0.6) +
        ggtitle("Source of transitional cells") +
        prism_theme() +
        theme(aspect.ratio = 1.6) +
        ylab("Transition probability (%)")

to_transitional_jitter_and_bar

pdf("./figures/epi/to_transitional_probability.pdf", height = 5.2, width = 3.2)
to_transitional_jitter_and_bar
dev.off()
```
```{r}
to_transitional_jitter_and_bar + transitional_jitter_and_bar + plot_layout(ncol = 2, nrow = 1) & theme(plot.margin = margin(5.5,105.5,5.5,5.5))
pdf("./figures/epi/main_transitions.pdf", height = 5, width = 10, bg = "transparent")
to_transitional_jitter_and_bar + transitional_jitter_and_bar + plot_layout(ncol = 2, nrow = 1) & theme(plot.margin = margin(5.5,100.5,5.5,5.5))
dev.off()
```

