---
title: "Plottings outputs of the cellrank analysis"
author: Nick Negretti
date: 12/07/20
output: rmarkdown::github_document
---

# Plot cellrank outputs of the lung endothelium

## Load libraries and helper functions
```{r, results="hide", message = FALSE}
setwd("~/postdoc/code/devo_scseq_github")
source("./helper_functions/globals.R")
source("./helper_functions/libraries.R")

opts_knit$set(root.dir = getwd())

source("./helper_functions/trajectory.R")
source("./helper_functions/cluster.R")
source("./helper_functions/colors.R")
source("./helper_functions/brackets.R")
source("./helper_functions/heatmaps.R")

plan("multiprocess", workers = N_WORKERS)
```
## Load data from merge and clean pipeline
```{r}
cellrank_out <- anndata::read_h5ad("./velocity/endo/only_metadata.h5ad")
#cellrank_out <- anndata::read_h5ad("./velocity/endo/after_cellrank.h5ad")
```

```{r}
cellrank_out
```


```{r}

endo_ms <- Matrix::readMM("./velocity/endo/endo_expression_Ms.mtx")
```


```{r}
gene <- "Car4"
include_celltypes <- c("Proliferating miEC", "miEC", "*Car4+* EC")
exp_over_time <- data.frame(expression = endo_ms[,colnames(cellrank_out) == gene],
                            Cluster = cellrank_out$obs$cell_subtype,
                            latent_time = cellrank_out$obs$latent_time
)

unique(exp_over_time$Cluster)

levels(exp_over_time$Cluster)[levels(exp_over_time$Cluster) == "Car4+"] <- "*Car4+* EC"
levels(exp_over_time$Cluster)[levels(exp_over_time$Cluster) == "Proliferating\nmiEC"] <- "Proliferating miEC"
exp_over_time$Cluster <- ordered(as.factor(exp_over_time$Cluster), c("Arterial maEC", "Venous maEC", "miEC", "*Car4+* EC", "Proliferating miEC", "Lymphatic"))

exp_over_time <- exp_over_time[exp_over_time$Cluster %in% include_celltypes,]

car4_exp <- ggplot(exp_over_time, aes(y = expression, x = latent_time, color = Cluster)) +
        geom_point(alpha = 0.5) +
        scale_color_manual(aesthetics = c("color", "fill"), values= color_category_20[3:5], guide = guide_legend(override.aes = list(size=3), order = 1)) +
        theme(legend.key = element_blank(),
              legend.text = element_markdown(size=14),
              legend.title = element_markdown(size=16),
              #axis.text.x  = element_text(size=14),
              axis.text.x = element_blank(),
              axis.ticks.x = element_blank(),
              axis.text.y = element_text(size=14),
              axis.title.x = element_text(size=14, vjust = -1),
              axis.title.y = element_text(size=14),
              panel.grid.major = element_blank(),
              panel.grid.minor = element_blank(),
              panel.background = element_rect(fill = "white", color = "black"),
              aspect.ratio = 0.8,
              plot.title = element_markdown(size = 16)
        ) +
        scale_x_continuous(breaks = c(0,1)) +
        ylab("Expression") +
        xlab("Latent time") +
        ggtitle(paste0("*", gene, "*"))

car4_exp

```

```{r}
gene <- "Kdr"
include_celltypes <- c("Proliferating miEC", "miEC", "*Car4+* EC")
exp_over_time <- data.frame(expression = endo_ms[,colnames(cellrank_out) == gene],
                            Cluster = cellrank_out$obs$cell_subtype,
                            latent_time = cellrank_out$obs$latent_time
)

unique(exp_over_time$Cluster)

levels(exp_over_time$Cluster)[levels(exp_over_time$Cluster) == "Car4+"] <- "*Car4+* EC"
levels(exp_over_time$Cluster)[levels(exp_over_time$Cluster) == "Proliferating\nmiEC"] <- "Proliferating miEC"
exp_over_time$Cluster <- ordered(as.factor(exp_over_time$Cluster), c("Arterial maEC", "Venous maEC", "miEC", "*Car4+* EC", "Proliferating miEC", "Lymphatic"))

exp_over_time <- exp_over_time[exp_over_time$Cluster %in% include_celltypes,]

kdr_exp <- ggplot(exp_over_time, aes(y = expression, x = latent_time, color = Cluster)) +
  geom_point(alpha = 0.5) +
  scale_color_manual(aesthetics = c("color", "fill"), values= color_category_20[3:5], guide = guide_legend(override.aes = list(size=3), order = 1)) +
  theme(legend.key = element_blank(),
        legend.text = element_markdown(size=14),
        legend.title = element_markdown(size=16),
        #axis.text.x  = element_text(size=14),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        axis.text.y = element_text(size=14),
        axis.title.x = element_text(size=14, vjust = -1),
        axis.title.y = element_text(size=14),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.background = element_rect(fill = "white", color = "black"),
        aspect.ratio = 0.8,
        plot.title = element_markdown(size = 16)
  ) +
  scale_x_continuous(breaks = c(0,1)) +
  ylab("Expression") +
  xlab("Latent time") +
  ggtitle(paste0("*", gene, "*"))

kdr_exp

```


```{r}
saveTiff("./figures/endo/latent_time/car4_kdr.tiff",
         car4_exp + kdr_exp + plot_layout(ncol = 2, nrow = 1, guides = "collect"),
         width = 15, height = 4)
```



```{r}
ggdata_endo <- data.frame(x = cellrank_out$obsm$X_umap[,1],
                     y = cellrank_out$obsm$X_umap[,2],
                          latent_time = cellrank_out$obs$latent_time,
                     group = as.character(cellrank_out$obs$cell_subtype),
                     timepoint = as.character(cellrank_out$obs$timepoint))
head(ggdata_endo)
colnames(ggdata_endo) <- c("x", "y", "latent_time", "group", "timepoint")
mean(ggdata_endo$latent_time)

end_latent_time <- ggplot(ggdata_endo %>% arrange(latent_time), aes(x = x, y = y, color = latent_time)) +
  geom_point(size = 0.5) +
  umap_theme() +
  theme(aspect.ratio = 1,
        legend.text=element_text(size=14),
        legend.title=element_text(size=14),
  plot.title = element_text(size = 18)) +
  scale_color_viridis(name = "Latent time", direction = -1) +
  xlab("UMAP_1") +
  ylab("UMAP_2") +
  ggtitle("Latent time")

end_latent_time

saveTiff("./figures/endo/latent_time_UMAP.tiff",
         end_latent_time,
         width = 6, height = 4.5)

```

```{r}
to_term <- cellrank_out$obsm$to_terminal_states

colnames(to_term) <- cellrank_out$uns$to_terminal_states_names

# Combine similar terminal types
to_term_unique <- to_term[,c(4,5,7,8)]

head(to_term_unique)

to_term <- cbind(to_term_unique, rowSums(to_term[,c(1, 6, 9)]), rowSums(to_term[,c(2, 3)]))


colnames(to_term) <- c(colnames(to_term_unique), "miEC", "Lymphatic")

```

```{r}
to_term <- as.data.frame(to_term)
to_term$timepoint <- ordered(as.factor(cellrank_out$obs$timepoint), c("E12", "E15", "E18", "P0", "P3", "P5", "P7", "P14"))

head(to_term)
head(to_term[cellrank_out$obs$cell_subtype == "Car4+",])

ggplot(melt(to_term[cellrank_out$obs$cell_subtype == "Car4+",]), aes(x = value, color = variable, fill = variable)) +
        geom_density(alpha = 0.3) +
        scale_x_continuous(limits = c(0.2,1)) +
        facet_grid(vars(timepoint), scales = "free")



car4_plot <- ggplot(melt(to_term[cellrank_out$obs$cell_subtype == "Car4+",]), aes(x = value, color = variable, fill = variable)) +
  geom_density(alpha = 0.3) +
  scale_x_continuous(limits = c(0.2,1)) +
        ggtitle("Fate probability of 'Car4+' cells")


miEC_plot <- ggplot(melt(to_term[cellrank_out$obs$cell_subtype == "miEC",]), aes(x = value, color = variable, fill = variable)) +
        geom_density(alpha = 0.3) +
        scale_x_continuous(limits = c(0.2,1)) +
        ggtitle("Fate probability of 'miEC' cells")

car4_plot + miEC_plot + patchwork::plot_layout(ncol = 1)

```


```{r}

summary_stats <- melt(to_term[cellrank_out$obs$cell_subtype == "miEC",]) %>% group_by(variable) %>% summarize(mean = mean(value) * 100,
                                                                                                              median = median(value) * 100,
                                                                                                              sd = sd(value) * 100,
                                                                                                              sem = (sd(value) / sqrt(length(value))) * 100,
                                                                                                              q1 = quantile(value, 1/4) * 100,
                                                                                                              q2 = quantile(value, 3/4) * 100,
                                                                                                              #ci1 = get_lower_ci(value) * 100,
                                                                                                              #ci2 = get_upper_ci(value) * 100
)

miEC_barplot <- ggplot(summary_stats, aes(y = mean, x = variable)) +
  geom_col() +
  geom_errorbar(aes(ymin = mean - sd, ymax = mean + sd), width = 0.2) +
  ggtitle("Fate of 'miEC' cells") +
  prism_theme() +
  theme(aspect.ratio = 1.6) +
  ylab("Transition probability")

miEC_barplot_noself <- ggplot(summary_stats[summary_stats$variable != "miEC",], aes(y = mean * 100, x = variable)) +
        geom_col() +
        geom_errorbar(aes(ymin = mean * 100 - sem * 100, ymax = mean * 100 + sem * 100), width = 0.2) +
        ggtitle("Fate of miEC cells") +
        prism_theme() +
        theme(aspect.ratio = 1.6) +
        ylab("Transition probability")

miEC_barplot + miEC_barplot_noself



to_term_long <- melt(to_term[cellrank_out$obs$cell_subtype == "miEC",])
to_term_long$value <- to_term_long$value * 100
to_term_long_above_zero <- to_term_long[to_term_long$value > 1,]


get_early_pct <- function(data, summary_stats, cell_group){
  timepoints <- data$obs$timepoint[data$obs$cell_subtype == cell_group]
  early <- sum(timepoints %in% c("E12", "E15", "E18")) * 100 / length(timepoints)
  return(early * summary_stats[summary_stats$variable == cell_group, "median"] / 100) # scale vals to max bar
}

for (type in unique(summary_stats$variable)){
  summary_stats[summary_stats$variable == type, "early"] <- get_early_pct(cellrank_out, summary_stats, type)
}


fate_miec_bar <- ggplot() +
        geom_col(data = summary_stats, aes(y = median, x = variable), color = "black", fill = "white") +
        #geom_col(data = summary_stats, aes(x = variable, y = early), fill = "#CDCDCD", width = 0.85) + # color early here, overlay on the other line
        geom_errorbar(data = summary_stats, aes(y = median, x = variable, ymin = q1, ymax = q2), width = 0.2) +
        #geom_boxplot(data = to_term_long, aes(y = value, x = variable), outlier.shape = NA, lwd=0.25) +
        #ggbeeswarm::geom_quasirandom(data = to_term_long, aes(y = value, x = variable), size = 0.8, shape = 1, alpha = 0.6) +
        ggtitle("Fate of miEC cells") +
        prism_theme() +
        theme(aspect.ratio = 1.6,
              plot.title = element_markdown(size = 14),
              axis.text.x = element_markdown(size = 14)
        ) +
        theme(aspect.ratio = 1.6) +
        ylab("Transition probability (%)")
fate_miec_bar

saveTiff("./figures/endo/fate_miEC.tiff",
         fate_miec_bar,
         width = 3, height = 5)

pdf("./figures/endo/fate_miEC.pdf", height = 5, width = 3)
fate_miec_bar
dev.off()

```

```{r}

to_term_orig <- cellrank_out$obsm$to_terminal_states

colnames(to_term_orig) <- cellrank_out$uns$to_terminal_states_names

ggdata_endo_to_Car4 <- data.frame(x = cellrank_out$obsm$X_umap[,1],
                             y = cellrank_out$obsm$X_umap[,2],
                             to_Car4 = to_term_orig[,"Car4+"],
                             cell_id = rownames(cellrank_out$obs))


to_Car4_time_plot <- ggplot(ggdata_endo_to_Car4 %>% arrange(to_Car4), aes(x = x, y = y, color = to_Car4)) + geom_point(alpha = 0.6, shape = 16) + umap_theme() + theme(aspect.ratio = 1) + scale_color_viridis(limits = c(0,max(ggdata_endo_to_Car4$to_Car4)))
to_Car4_time_plot

saveRDS(ggdata_endo_to_Car4, "./velocity/endo/data/endo_car4_prob.rds")
```

```{r}

from_initial <- cellrank_out$obsm$from_initial_states

colnames(from_initial) <- cellrank_out$uns$from_initial_states_names

head(from_initial)
# Combine similar terminal types
#from_initial_no_T2 <- from_initial[,c(1,2,3,5)]

#from_initial <- cbind(from_initial_no_T2, rowSums(from_initial[,c(4,6,7)])) # Merge the Type II fates
#colnames(from_initial) <- c(colnames(from_initial_no_T2), "Type II")
from_initial <- as.data.frame(from_initial)
from_initial$timepoint <- ordered(as.factor(cellrank_out$obs$timepoint), c("E12", "E15", "E18", "P0", "P3", "P5", "P7", "P14"))

head(from_initial[cellrank_out$obs$cell_subtype == "Car4+",])


to_car4_plot <- ggplot(melt(from_initial[cellrank_out$obs$cell_subtype == "Car4+",]), aes(x = value, color = variable, fill = variable)) +
  geom_density(alpha = 0.3) +
  scale_x_continuous(limits = c(0.05,1)) +
  ggtitle("Fate probability towards 'Car4+' cells")

to_car4_plot

```

```{r}

colnames(from_initial)[2] <- "Proliferating miEC"
colnames(from_initial)[5] <- "*Car4*+"
summary_stats <- melt(from_initial[cellrank_out$obs$cell_subtype == "Car4+",]) %>% group_by(variable) %>% summarize(mean = mean(value) * 100,
                                                                                                                    median = median(value) * 100,
                                                                                                                    sd = sd(value) * 100,
                                                                                                                    sem = (sd(value) / sqrt(length(value))) * 100,
                                                                                                                    q1 = quantile(value, 1/4) * 100,
                                                                                                                    q2 = quantile(value, 3/4) * 100,
)

transitional_barplot <- ggplot(summary_stats, aes(y = mean, x = variable)) +
        geom_col() +
        geom_errorbar(aes(ymin = mean - sem, ymax = mean + sem), width = 0.2) +
        ggtitle("Towards 'Car4+' cells") +
        prism_theme() +
        theme(aspect.ratio = 1.6) +
        ylab("Transition probability")

transitional_barplot

from_initial_long <- melt(from_initial[cellrank_out$obs$cell_subtype == "Car4+",])
from_initial_long$value <- from_initial_long$value * 100
from_initial_long_above_zero <- from_initial_long[from_initial_long$value > 1,]

get_early_pct <- function(data, summary_stats, cell_group){
  timepoints <- data$obs$timepoint[data$obs$cell_subtype == cell_group]
  early <- sum(timepoints %in% c("E12", "E15", "E18")) * 100 / length(timepoints)
  return(early * summary_stats[summary_stats$variable == cell_group, "median"] / 100) # scale vals to max bar
}

for (type in unique(summary_stats$variable)){
  summary_stats[summary_stats$variable == type, "early"] <- get_early_pct(cellrank_out, summary_stats, type)
}

source_car4_bar <- ggplot() +
        geom_col(data = summary_stats, aes(y = median, x = variable), color = "black", fill = "white") +

        #geom_col(data = summary_stats, aes(x = variable, y = early), fill = "#CDCDCD", width = 0.84) + # color early here, overlay on the other line
        geom_errorbar(data = summary_stats, aes(y = median, x = variable, ymin = q1, ymax = q2), width = 0.6) +
        #geom_boxplot(data = from_initial_long, aes(y = value, x = variable), outlier.shape = NA, lwd=0.25) +
        #ggbeeswarm::geom_quasirandom(data = from_initial_long, aes(y = value, x = variable), size = 0.8, shape = 1, alpha = 0.6) +
        ggtitle("Source of *Car4*+ cells") +
        prism_theme() +
        theme(aspect.ratio = 1.6,
              plot.title = element_markdown(size = 14),
              axis.text.x = element_markdown(size = 14)
        ) +
        ylab("Transition probability (%)")

source_car4_bar

saveTiff("./figures/endo/to_car4_probability.tiff",
         source_car4_bar,
         width = 3, height = 5)

pdf("./figures/endo/to_car4_probability.pdf", height = 5, width = 3)
source_car4_bar
dev.off()

```

```{r}
saveTiff("./figures/endo/fate_miEC_source_car4.tiff",
         fate_miec_bar + source_car4_bar + plot_layout(ncol = 2, nrow = 1) & theme(plot.margin = margin(5.5,105.5,5.5,5.5)),
         width = 15, height = 4)


pdf("./figures/endo/fate_miEC_source_car4.pdf", height = 4, width = 15)
fate_miec_bar + source_car4_bar + plot_layout(ncol = 2, nrow = 1) & theme(plot.margin = margin(5.5,105.5,5.5,5.5))
dev.off()

```
